name: valpolab
channels:
  - conda-forge
dependencies:
  - python=3
  - arm_pyart
  - numpy
  - matplotlib
  - siphon
  - xarray
  - netCDF4
  - cartopy
  - pint
  - pandas
  - eofs
  - jupyterlab
  - pip
  - pip:
     - metpy==1.0rc2
